#!/bin/sh
#
# aws-swap-init
#
# chkconfig: 2345 99 10
# description: Check to see if epemeral disk is mounted. If it is, and swap doesn't exist, \
#              create swap equivalent to memory on the ephemeral drive. If it isn't, and \
#              exist, create 4096MB of swap on /.
# processname: aws-swap-init
#
### BEGIN INIT INFO
# Provides:          aws-swap-init
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ensure swap is created and enabled
# Description:       Check to see if epemeral disk is mounted. If it is, and swap doesn't exist,
#                    create swap equivalent to memory on the ephemeral drive. If it isn't, and
#                    exist, create 512MB of swap on /.
### END INIT INFO
# Copyright 2012 Corsis
#    http://www.corsis.com/
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

DEFAULTSIZE=4194304

start () {
    # Check to see if there is swap mounted right now
    # If there is, we're done here
    ISSWAP=`/bin/cat /proc/meminfo | /bin/grep SwapTotal | /usr/bin/awk '{print $2}'`
    if [ $ISSWAP -ne 0 ]
    then
        exit 0
    fi

    # What OS are we running?
    if [ -f /etc/system-release -o -f /etc/redhat-release ]
    then
        OSTYPE="amzn"
    elif [ -f /etc/lsb-release ]
    then
        OSTYPE="ubuntu"
    fi

    # Set the target directory. If unsupported platform, use root
    case "$OSTYPE" in
        amzn)
            TARGET="/media/ephemeral0"
            ;;
        ubuntu)
            TARGET="/mnt"
            ;;
        *)
            TARGET="/"
            ;;
    esac

    # Does a swapfile already exist? If so, activate and be done
    if [ -f $TARGET/swapfile00 ]
    then
        /sbin/swapon $TARGET/swapfile00
        exit 0
    fi
 
    # OK, so there's no existing swapfile. Let's make one and activate it.

    # If we're on an unsupported OS, or ephemeral disk isn't mounted, use a safe
    # default size. Otherwise, use RAM size
    if [ $TARGET = "/" ]
    then
        SIZE=$DEFAULTSIZE
    else
        /bin/mount | grep -q " on $TARGET type "
        if [ $? -eq 0 ]
        then
            SIZE=`/bin/cat /proc/meminfo | /bin/grep "^MemTotal" | /usr/bin/awk '{print $2}'`
        else
            SIZE=$DEFAULTSIZE
            TARGET="/"
        fi
    fi
        
    # OK, time to get down to business.
    /bin/dd if=/dev/zero of=$TARGET/swapfile00 bs=1024 count=$SIZE
    /sbin/mkswap $TARGET/swapfile00
    /sbin/swapon $TARGET/swapfile00
}

stop () {
    exit 0
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 2
esac
exit $?
